// List Users
export const GET_LIST_USER_REQUEST = "GET_LIST_USER";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_FAILURE = "GET_LIST_USER_FAILURE";

// Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

// Register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

// Get list banner
export const GET_LIST_BANNER_REQUEST = "GET_LIST_BANNER_REQUEST";
export const GET_LIST_BANNER_SUCCESS = "GET_LIST_BANNER_SUCCESS";
export const GET_LIST_BANNER_FAILURE = "GET_LIST_BANNER_FAILURE";

// Get list movies - category
export const GET_LIST_MOVIES_REQUEST = "GET_LIST_MOVIES_REQUEST";
export const GET_LIST_MOVIES_SUCCESS = "GET_LIST_MOVIES_SUCCESS";
export const GET_LIST_MOVIES_FAILURE = "GET_LIST_MOVIES_FAILURE";

// Edit user
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

// Delete user
// export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
// export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
// export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
